CREATE TABLE IF NOT EXISTS "link" (
  "name" VARCHAR NOT NULL UNIQUE,
  "url" VARCHAR NOT NULL UNIQUE,
  "hits" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
