PRAGMA journal_mode=WAL;
PRAGME wal_autocheckpoint=100;
CREATE TABLE IF NOT EXISTS "link" (
  "name" VARCHAR NOT NULL UNIQUE,
  "url" VARCHAR NOT NULL UNIQUE,
  "hits" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "idx_link_hits" on link("hits" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "idx_link_name" ON link("name");
