#!/usr/bin/env bash

NAME="$1"
URL="$2"
CERT=""
SERVER=""

echo "Broken. The webserver 404s when receiving %s in the URL-encoded text"
exit

if [[ -z "$CERT" ]]; then
    echo "Please edit $0 so it points to your client certificate."
    exit
fi

if [[ -z "$SERVER" ]]; then
    echo "Please edit $0 so it points to your server."
    exit
fi

ENCODED=$( echo "$URL" | perl -MURI::Escape -wlne 'print uri_escape $_' )
curl -E $CERT https://$SERVER/links/$NAME/edit/$ENCODED
