#!/usr/bin/env bash

NAME="$1"
CERT="/home/jayed/keys/meangrape_hackage.pem"
SERVER=""

if [[ -z "$CERT" ]]; then
    echo "Please edit $0 so it points to your client certificate."
    exit
fi

if [[ -z "$SERVER" ]]; then
    echo "Please edit $0 so it points to your server."
    exit
fi

curl -E $CERT -i -s "https://$SERVER/$NAME" | grep Location | cut -f2 -d' '

