#!/usr/bin/env bash

CERT="/home/jayed/keys/meangrape_hackage.pem"
SERVER=""

if [[ -z "$CERT" ]]; then
    echo "Please edit $0 so it points to your client certificate."
    exit
fi

if [[ -z "$SERVER" ]]; then
    echo "Please edit $0 so it points to your server."
    exit
fi

IFS=",[]"
links=($( curl -E $CERT -s http://$SERVER ))
unset IFS
printf '%s\n' "${links[@]}"

