#!/usr/bin/env bash

CERT=""
SERVER=""

if [[ -z "$CERT" ]]; then
    echo "Please edit $0 so it points to your client certificate."
    exit
fi

if [[ -z "$SERVER" ]]; then
    echo "Please edit $0 so it points to your server."
    exit
fi

# Bash arrays ahead
links=$( curl -E $CERT -s https://$SERVER )
declare -a html=$( perl -MHTML::Strip -lpe '$hs=HTML::Strip->new(); $_ = $hs->parse( $_ )' <<< "$links" )
echo "${html[@]}"
