#!/usr/bin/env bash

CERT=""
SERVER=""

if [[ -z "$CERT" ]]; then
    echo "Please edit $0 so it points to your client certificate."
    exit
fi

if [[ -z "$SERVER" ]]; then
    echo "Please edit $0 so it points to your server."
    exit
fi

echo "$0 is broken."
echo "This endpoint returns HTML now not JSON."
exit

# Bash arrays ahead
links=($( curl -E $CERT -s https://$SERVER ))

stripped=$( echo "$URL" | perl -MHTML::Strip -wlne 'my $hs=HTML::Strip.new(); my
$clean=$hs->parse($_)' )

echo $stripped
